services:
  - type: web
    name: math-battle-server
    env: node
    rootDir: MathBattle
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
